package com.jimi.bude.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;


/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("action_log", "id", ActionLog.class);
		arp.addMapping("arm", "name", Arm.class);
		arp.addMapping("bead", "id", Bead.class);
		arp.addMapping("body", "id", Body.class);
		arp.addMapping("error_log", "id", ErrorLog.class);
		arp.addMapping("face", "id", Face.class);
		// Composite Primary Key order: arm_name,name
		arp.addMapping("finger", "arm_name,name", Finger.class);
		arp.addMapping("head", "id", Head.class);
		arp.addMapping("socket_log", "id", SocketLog.class);
		arp.addMapping("soul", "id", Soul.class);
		arp.addMapping("system_config", "id", SystemConfig.class);
		arp.addMapping("user", "id", User.class);
	}
}
