package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseActionLog;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActionLog extends BaseActionLog<ActionLog> {

	public static final ActionLog dao = new ActionLog().dao();
}
