package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseArm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Arm extends BaseArm<Arm> {
	public static final Arm dao = new Arm().dao();
}
