package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseBead;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bead extends BaseBead<Bead> {
	public static final Bead dao = new Bead().dao();
}
