package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseBody;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Body extends BaseBody<Body> {

	public static final Body dao = new Body().dao();
}
