package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseErrorLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ErrorLog extends BaseErrorLog<ErrorLog> {
	public static final ErrorLog dao = new ErrorLog().dao();
}
