package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseFace;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Face extends BaseFace<Face> {

	public static final Face dao = new Face().dao();
}
