package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseFinger;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Finger extends BaseFinger<Finger> {

	public static final Finger dao = new Finger().dao();
}
