package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseHead;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Head extends BaseHead<Head> {

	public static final Head dao = new Head().dao();
}
