package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseSocketLog;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SocketLog extends BaseSocketLog<SocketLog> {

	public static final SocketLog dao = new SocketLog().dao();
}
