package com.jimi.bude.model;

import com.jimi.bude.model.base.BaseSoul;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Soul extends BaseSoul<Soul> {

	public static final Soul dao = new Soul().dao();
}
