package com.jimi.bude.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFace<M extends BaseFace<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M) this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setHeadId(java.lang.Integer headId) {
		set("head_id", headId);
		return (M) this;
	}

	public java.lang.Integer getHeadId() {
		return getInt("head_id");
	}

}
