package com.jimi.bude.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseArm<M extends BaseArm<M>> extends Model<M> implements IBean {

	public M setName(java.lang.String name) {
		set("name", name);
		return (M) this;
	}


	public java.lang.String getName() {
		return getStr("name");
	}


	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M) this;
	}


	public java.lang.String getIp() {
		return getStr("ip");
	}


	public M setServerPort(java.lang.Integer serverPort) {
		set("server_port", serverPort);
		return (M) this;
	}


	public java.lang.Integer getServerPort() {
		return getInt("server_port");
	}


	public M setLastPingTime(java.util.Date lastPingTime) {
		set("last_ping_time", lastPingTime);
		return (M) this;
	}


	public java.util.Date getLastPingTime() {
		return get("last_ping_time");
	}


	public M setBodyId(java.lang.Integer bodyId) {
		set("body_id", bodyId);
		return (M) this;
	}


	public java.lang.Integer getBodyId() {
		return getInt("body_id");
	}

}
