package com.jimi.bude.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSocketLog<M extends BaseSocketLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setSenderIp(java.lang.String senderIp) {
		set("sender_ip", senderIp);
		return (M) this;
	}


	public java.lang.String getSenderIp() {
		return getStr("sender_ip");
	}


	public M setReceiverIp(java.lang.String receiverIp) {
		set("receiver_ip", receiverIp);
		return (M) this;
	}


	public java.lang.String getReceiverIp() {
		return getStr("receiver_ip");
	}


	public M setType(java.lang.String type) {
		set("type", type);
		return (M) this;
	}


	public java.lang.String getType() {
		return getStr("type");
	}


	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M) this;
	}


	public java.lang.String getMessage() {
		return getStr("message");
	}


	public M setTime(java.util.Date time) {
		set("time", time);
		return (M) this;
	}


	public java.util.Date getTime() {
		return get("time");
	}

}
