package com.jimi.bude.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFinger<M extends BaseFinger<M>> extends Model<M> implements IBean {

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setArmName(java.lang.String armName) {
		set("arm_name", armName);
		return (M)this;
	}
	
	public java.lang.String getArmName() {
		return getStr("arm_name");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setLastPingTime(java.util.Date lastPingTime) {
		set("last_ping_time", lastPingTime);
		return (M)this;
	}
	
	public java.util.Date getLastPingTime() {
		return get("last_ping_time");
	}

	public M setBeadId(java.lang.Integer beadId) {
		set("bead_id", beadId);
		return (M)this;
	}
	
	public java.lang.Integer getBeadId() {
		return getInt("bead_id");
	}

}
