package com.jimi.bude.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseActionLog<M extends BaseActionLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M) this;
	}


	public java.lang.String getIp() {
		return getStr("ip");
	}


	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M) this;
	}


	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}


	public M setMessage(java.lang.String message) {
		set("message", message);
		return (M) this;
	}


	public java.lang.String getMessage() {
		return getStr("message");
	}


	public M setResultCode(java.lang.Integer resultCode) {
		set("result_code", resultCode);
		return (M) this;
	}


	public java.lang.Integer getResultCode() {
		return getInt("result_code");
	}


	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M) this;
	}


	public java.lang.String getUrl() {
		return getStr("url");
	}


	public M setTime(java.util.Date time) {
		set("time", time);
		return (M) this;
	}


	public java.util.Date getTime() {
		return get("time");
	}

}
