package com.jimi.bude.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;


/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSoul<M extends BaseSoul<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M) this;
	}


	public java.lang.Integer getId() {
		return getInt("id");
	}


	public M setKey(java.lang.String key) {
		set("key", key);
		return (M) this;
	}


	public java.lang.String getKey() {
		return getStr("key");
	}


	public M setValue(java.lang.String value) {
		set("value", value);
		return (M) this;
	}


	public java.lang.String getValue() {
		return getStr("value");
	}


	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M) this;
	}


	public java.lang.Integer getType() {
		return getInt("type");
	}


	public M setScope(java.lang.Integer scope) {
		set("scope", scope);
		return (M) this;
	}


	public java.lang.Integer getScope() {
		return getInt("scope");
	}


	public M setFingerName(java.lang.String fingerName) {
		set("finger_name", fingerName);
		return (M) this;
	}


	public java.lang.String getFingerName() {
		return getStr("finger_name");
	}


	public M setArmName(java.lang.String armName) {
		set("arm_name", armName);
		return (M) this;
	}


	public java.lang.String getArmName() {
		return getStr("arm_name");
	}


	public M setBodyId(java.lang.Integer bodyId) {
		set("body_id", bodyId);
		return (M) this;
	}


	public java.lang.Integer getBodyId() {
		return getInt("body_id");
	}

}
